

#????
telegram.token=1116496780:AAH8HZ8kDNoSQW3LNXKM8ladh434hCJfEls
db.url=jdbc:postgresql://localhost:5432/sexshoptest
db.user=postgres
db.password=1234

# prod
#db.url=jdbc:postgresql://62.60.151.13:5432/sexshop
#db.user=zrezlorez
#db.password=dickrealybigpasswordforthisjavasoft
#telegram.token=1116496780:AAH8HZ8kDNoSQW3LNXKM8ladh434hCJfEls
#discord.token=MTA2NTMyMTM1MDY2OTAyOTQ2Ng.G-tnAF.OH6pexLYNwEp7I1C8qDQ5LYr9eSvC1CgpLKnOw

proxy.isEnabled=true
proxy.host=62.60.151.13
proxy.port=49429
proxy.username=zrezlorez
proxy.password=test

admin.telegramUserIds=1050257214
admin.discordUserIds=275213804894420992
