db.url=jdbc:postgresql://62.60.151.13:5432/sexshop
db.user=zrezlorez
db.password=dickrealybigpasswordforthisjavasoft

proxy.isEnabled=false
proxy.host=62.60.151.13
proxy.port=49429
proxy.username=zrezlorez
proxy.password=test