create table if not exists activity_stats
(
    id            bigint generated by default as identity,
    activity_date date        not null,
    message_count bigint      not null,
    platform      varchar(16) not null,
    player_id     bigint      not null,
    scope_id      bigint      not null,
    voice_seconds bigint      not null,
    primary key (id),
    constraint uk_activity_stats_player_platform_scope_date
        unique (player_id, platform, scope_id, activity_date),
    constraint activity_stats_platform_check
        check ((platform)::text = ANY ((ARRAY ['TELEGRAM'::character varying, 'DISCORD'::character varying])::text[]))
);

create table if not exists conversation_participants
(
    id        bigint generated by default as identity,
    platform  varchar(16) not null,
    player_id bigint      not null,
    scope_id  bigint      not null,
    primary key (id),
    constraint uk_conversation_participants_player_platform_scope
        unique (player_id, platform, scope_id),
    constraint conversation_participants_platform_check
        check ((platform)::text = ANY ((ARRAY ['TELEGRAM'::character varying, 'DISCORD'::character varying])::text[]))
);

create table if not exists conversation_settings
(
    id                 bigint generated by default as identity,
    growth_style       varchar(64) not null,
    manager_profile_id bigint,
    platform           varchar(16) not null,
    scope_id           bigint      not null,
    primary key (id),
    constraint uk_conversation_settings_platform_scope
        unique (platform, scope_id),
    constraint conversation_settings_platform_check
        check ((platform)::text = ANY ((ARRAY ['TELEGRAM'::character varying, 'DISCORD'::character varying])::text[]))
);

create table if not exists link_codes
(
    id              bigint generated by default as identity,
    code            varchar(16)  not null,
    expires_at      timestamp(6) not null,
    player_id       bigint       not null,
    source_platform varchar(16)  not null,
    primary key (id),
    constraint code_constraint
        unique (code),
    constraint link_codes_source_platform_check
        check ((source_platform)::text = ANY
               ((ARRAY ['TELEGRAM'::character varying, 'DISCORD'::character varying])::text[]))
);

create table if not exists players
(
    id                           bigint generated by default as identity,
    discord_tag                  varchar(255),
    discord_user_id              bigint,
    last_ability_time            timestamp(6),
    last_grow_time               timestamp(6),
    pending_crit_chance_modifier double precision default 0 not null,
    pending_fail_chance_modifier double precision default 0 not null,
    pending_growth_modifier      double precision default 0 not null,
    size                         double precision not null,
    telegram_chat_id             bigint,
    telegram_display_name        varchar(255),
    telegram_username            varchar(255),
    status                       varchar(64),
    status_until                 timestamptz,
    primary key (id),
    constraint uk_players_telegram_chat_id
        unique (telegram_chat_id),
    constraint uk_players_discord_user_id
        unique (discord_user_id)
);

create table if not exists voice_sessions
(
    id         bigint generated by default as identity,
    platform   varchar(16)  not null,
    player_id  bigint       not null,
    scope_id   bigint       not null,
    started_at timestamp(6) not null,
    primary key (id),
    constraint uk_voice_sessions_player_platform
        unique (player_id, platform),
    constraint voice_sessions_platform_check
        check ((platform)::text = ANY ((ARRAY ['TELEGRAM'::character varying, 'DISCORD'::character varying])::text[]))
);


