alter table player_behavior_stats add column action_target_id bigint;
alter table player_behavior_stats add column same_ability_and_target_streak bigint default 0;

create table if not exists telegram_callback_request (
    id bigserial primary key,
    scope_id bigint,
    message_id bigint,
    status varchar(50),
    expired_at timestamp,
    complete_at timestamp,
    created_at timestamp not null default current_timestamp
);

create table if not exists telegram_callback_vote (
    id bigserial primary key,
    request_id bigint not null,
    player_id bigint not null,
    player_decision varchar(50),
    voted_at timestamp,
    auto_selected boolean,
    is_mother boolean
);

create table if not exists children
(
    id            bigint generated by default as identity,
    scope_id      bigint      not null,
    first_player  bigint      not null,
    second_player bigint      not null,
    status        varchar(32) not null,
    health        integer     not null,
    streak        integer     not null,
    created_at    timestamptz not null default now(),
    primary key (id),
    constraint uk_children_scope_parents
        unique (scope_id, first_player, second_player)
);

create table if not exists children_care
(
    id                   bigint generated by default as identity,
    children_id          bigint  not null,
    care_date            date    not null,
    first_parent_action  varchar(32),
    second_parent_action varchar(32),
    resolved             boolean not null default false,
    resolved_at          timestamptz,
    message_id           bigint,
    successful           boolean,
    success_chance       double precision,
    primary key (id),
    constraint uk_children_care_children_date
        unique (children_id, care_date)
);
